=== JuanCruzMateos/OrgaDeDatos/Practica/Guia07/xml/factura.dtd
<!ELEMENT factura (tipo, fecha, numero, tipoPago, empresa, cliente, renglones, infoTotal)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT tipoPago (#PCDATA)>
<!ELEMENT empresa (nombre, direccion, cuit, datosContacto)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT cuit (#PCDATA)>
<!ELEMENT datosContacto (#PCDATA)>
<!ELEMENT cliente (nombre, direccion, cuit, datosContacto, tipo)>
<!ELEMENT renglones (renglon+)>
<!ELEMENT renglon (codigo, descripcion, cantidad, precio, iva, importe)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT infoTotal (tipoDescuento, descuento, total)>
<!ELEMENT tipoDescuento (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== JuanCruzMateos/OrgaDeDatos/Practica/Guia07/xml/factura.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE factura SYSTEM "factura.dtd">

<factura>
    <tipo>A</tipo>
    <fecha>2021-10-26</fecha>
    <numero>14253699852114</numero>
    <tipoPago>Efectivo</tipoPago>
    <empresa>
        <nombre>evil corp</nombre>
        <direccion>calle falsa 123</direccion>
        <cuit>123456</cuit>
        <datosContacto>No tenemos</datosContacto>
    </empresa>
    <cliente>
        <nombre>Juan Cruz</nombre>
        <direccion>calle falsa 143</direccion>
        <cuit>1478523695</cuit>
        <datosContacto>Tampoco tiene</datosContacto>
        <tipo>Consumidor Final</tipo>
    </cliente>
    <renglones>
        <renglon>
            <codigo>FF1421369</codigo>
            <descripcion>Empanada</descripcion>
            <cantidad>100</cantidad>
            <precio>150.0</precio>
            <iva>0.21</iva>
            <importe>18150.0</importe>
        </renglon>
    </renglones>
    <infoTotal>
        <tipoDescuento>0</tipoDescuento>
        <descuento>0.0</descuento>
        <total>18150.0</total>
    </infoTotal>
</factura>
